#!/usr/bin/env bash
# Starting Apache
service apache2 start

# Check if Apache is running
if service apache2 status | grep -q "running"; then
    echo "apache2 is running"
else
    echo "Failed to start apache2"
    exit 1
fi
