#!/usr/bin/env bash
# install nginx on web-01, listening to port 80
# and return a page containg the expected string

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 80

#reassign ownership so that they can be writeable
sudo chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.html
