#!/usr/bin/env bash
# Check if Nginx is installed

sudo apt-get -y update
sudo apt-get -y install nginx

# redirection config
replacement="server_name _;\\
    rewrite ^/redirect_me https://github.com/H3PHZY/ permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx start
